---
abstract: 'compose functions into one function'
author:
  - 'shelling <navyblueshellingford@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Function-Composition
no_index:
  directory:
    - inc
    - t
    - xt
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: https://github.com/shelling/function-composition
version: 0.0.2
